name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Fun-with-orthoprojection.tex
          working_directory: src/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src/Fun-with-orthoprojection.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
